# Generated by Django 5.1.1 on 2025-05-15 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='menu_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Menu Name'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='named_url',
            field=models.CharField(blank=True, max_length=255, verbose_name='Named URL'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='url',
            field=models.CharField(blank=True, max_length=255, verbose_name='URL'),
        ),
        migrations.AlterUniqueTogether(
            name='menuitem',
            unique_together={('menu_name', 'parent', 'name')},
        ),
    ]
